; Generated by scripts/generate-windows-open-with.mjs. Do not edit directly.
; Morflo registers only as an Open with candidate. It never changes user defaults.

!define MORFLO_PROGID "Morflo.Media.1"
!define MORFLO_APP_NAME "Morflo"
!define MORFLO_APP_DESCRIPTION "Local image and video conversion"
!define MORFLO_FILE_DESCRIPTION "Media file for Morflo"
!define MORFLO_EXECUTABLE "morflo.exe"

!macro MORFLO_REGISTER_EXTENSION EXT
  WriteRegStr HKCU "Software\Classes\.${EXT}\OpenWithProgids" "${MORFLO_PROGID}" ""
  WriteRegStr HKCU "Software\Morflo\Capabilities\FileAssociations" ".${EXT}" "${MORFLO_PROGID}"
  WriteRegStr HKCU "Software\Classes\Applications\${MORFLO_EXECUTABLE}\SupportedTypes" ".${EXT}" ""
!macroend

!macro MORFLO_UNREGISTER_EXTENSION EXT
  DeleteRegValue HKCU "Software\Classes\.${EXT}\OpenWithProgids" "${MORFLO_PROGID}"
  DeleteRegValue HKCU "Software\Morflo\Capabilities\FileAssociations" ".${EXT}"
  DeleteRegValue HKCU "Software\Classes\Applications\${MORFLO_EXECUTABLE}\SupportedTypes" ".${EXT}"
!macroend

!macro NSIS_HOOK_POSTINSTALL
  WriteRegStr HKCU "Software\Classes\${MORFLO_PROGID}" "" "${MORFLO_FILE_DESCRIPTION}"
  WriteRegStr HKCU "Software\Classes\${MORFLO_PROGID}" "AllowSilentDefaultTakeOver" ""
  WriteRegStr HKCU "Software\Classes\${MORFLO_PROGID}\DefaultIcon" "" "$INSTDIR\${MORFLO_EXECUTABLE},0"
  WriteRegStr HKCU "Software\Classes\${MORFLO_PROGID}\shell" "" "open"
  WriteRegStr HKCU "Software\Classes\${MORFLO_PROGID}\shell\open" "" "Open with ${MORFLO_APP_NAME}"
  WriteRegStr HKCU "Software\Classes\${MORFLO_PROGID}\shell\open\command" "" "$\"$INSTDIR\${MORFLO_EXECUTABLE}$\" $\"%1$\""
  WriteRegStr HKCU "Software\Classes\Applications\${MORFLO_EXECUTABLE}" "FriendlyAppName" "${MORFLO_APP_NAME}"
  WriteRegStr HKCU "Software\Classes\Applications\${MORFLO_EXECUTABLE}\shell\open\command" "" "$\"$INSTDIR\${MORFLO_EXECUTABLE}$\" $\"%1$\""
  WriteRegStr HKCU "Software\Morflo\Capabilities" "ApplicationName" "${MORFLO_APP_NAME}"
  WriteRegStr HKCU "Software\Morflo\Capabilities" "ApplicationDescription" "${MORFLO_APP_DESCRIPTION}"
  WriteRegStr HKCU "Software\RegisteredApplications" "${MORFLO_APP_NAME}" "Software\Morflo\Capabilities"
  !insertmacro MORFLO_REGISTER_EXTENSION "png"
  !insertmacro MORFLO_REGISTER_EXTENSION "jpg"
  !insertmacro MORFLO_REGISTER_EXTENSION "jpeg"
  !insertmacro MORFLO_REGISTER_EXTENSION "webp"
  !insertmacro MORFLO_REGISTER_EXTENSION "bmp"
  !insertmacro MORFLO_REGISTER_EXTENSION "tif"
  !insertmacro MORFLO_REGISTER_EXTENSION "tiff"
  !insertmacro MORFLO_REGISTER_EXTENSION "avif"
  !insertmacro MORFLO_REGISTER_EXTENSION "ico"
  !insertmacro MORFLO_REGISTER_EXTENSION "mp4"
  !insertmacro MORFLO_REGISTER_EXTENSION "mov"
  !insertmacro MORFLO_REGISTER_EXTENSION "mkv"
  !insertmacro MORFLO_REGISTER_EXTENSION "webm"
  System::Call "shell32::SHChangeNotify(i 0x08000000, i 0x1000, p 0, p 0)"
!macroend

!macro NSIS_HOOK_PREUNINSTALL
  !insertmacro MORFLO_UNREGISTER_EXTENSION "png"
  !insertmacro MORFLO_UNREGISTER_EXTENSION "jpg"
  !insertmacro MORFLO_UNREGISTER_EXTENSION "jpeg"
  !insertmacro MORFLO_UNREGISTER_EXTENSION "webp"
  !insertmacro MORFLO_UNREGISTER_EXTENSION "bmp"
  !insertmacro MORFLO_UNREGISTER_EXTENSION "tif"
  !insertmacro MORFLO_UNREGISTER_EXTENSION "tiff"
  !insertmacro MORFLO_UNREGISTER_EXTENSION "avif"
  !insertmacro MORFLO_UNREGISTER_EXTENSION "ico"
  !insertmacro MORFLO_UNREGISTER_EXTENSION "mp4"
  !insertmacro MORFLO_UNREGISTER_EXTENSION "mov"
  !insertmacro MORFLO_UNREGISTER_EXTENSION "mkv"
  !insertmacro MORFLO_UNREGISTER_EXTENSION "webm"
  DeleteRegValue HKCU "Software\RegisteredApplications" "${MORFLO_APP_NAME}"
  DeleteRegKey HKCU "Software\Morflo\Capabilities"
  DeleteRegKey /ifempty HKCU "Software\Morflo"
  DeleteRegKey HKCU "Software\Classes\Applications\${MORFLO_EXECUTABLE}"
  DeleteRegKey HKCU "Software\Classes\${MORFLO_PROGID}"
  System::Call "shell32::SHChangeNotify(i 0x08000000, i 0x1000, p 0, p 0)"
!macroend
